### ISSUE TITLE
Log in link issue

### ISSUE THREAD

**Issue by gregfitch** [openstax/kinetic#96]
The log in link on staging.kinetic.openstax.org is currently `https://accounts-staging.openstax.org/accounts/i/login/?r=https%3A%2F%2Fstaging.kinetic.openstax.org%2F`, which doesn't work.

![Screen Shot 2021-12-09 at 10.32.35 AM.png](https://images.zenhubusercontent.com/5b4cef1a8f15f517ad0533a2/b2b4e047-6d96-4f6e-a1d1-d9cff321d525)

**Comment by Dantemss** [comment]
staging.openstax.org/accounts is the right link

**Comment by reedstrm** [comment]
Can I get steps-to-replicate? If I start from https://cms-staging.openstax.org/kinetic/ without a login cookie, all the login buttons work.

**Comment by reedstrm** [comment]
Ah nevermind, I see it now - it's from going direct to staging.kinetic.openstax.org, like it says at the top

**Comment by gregfitch** [comment]
Verified on Staging

**Comment by reedstrm** [comment]
This has been fixed at some point (going direct to https://staging.kinetic.openstax.org in a private window, the login buttons work)
